import ThesisBlock from './ThesisBlock';
import MemoSection from './MemoSection';
import KeyFiguresTable from './KeyFiguresTable';
import PriceWindow from './PriceWindow';
import RisksList from './RisksList';
import DataCaveats from './DataCaveats';
import Sources from './Sources';

function Prose({ children }) {
  return (
    <p className="font-serif text-base leading-relaxed text-stone-800 whitespace-pre-wrap">
      {children}
    </p>
  );
}

export default function Memo({ data }) {
  const { memo, sources } = data;

  return (
    <div className="max-w-document mx-auto px-6 py-10">
      <ThesisBlock
        thesis={memo.thesis}
        companyName={memo.companyName}
        ticker={memo.ticker}
        asOfDate={memo.asOfDate}
      />

      <MemoSection title="Business Overview">
        <Prose>{memo.businessOverview.summary}</Prose>
      </MemoSection>

      <MemoSection title="Financial Highlights">
        <Prose>{memo.financialHighlights.summary}</Prose>
        <KeyFiguresTable figures={memo.financialHighlights.keyFigures} />
      </MemoSection>

      <MemoSection title="Valuation Context">
        <Prose>{memo.valuationContext.summary}</Prose>
        <PriceWindow priceWindow={memo.valuationContext.priceWindow} />
      </MemoSection>

      <MemoSection title="Macro Context">
        <Prose>{memo.macroContext.summary}</Prose>
      </MemoSection>

      <MemoSection title="Key Risks">
        <RisksList risks={memo.keyRisks.risks} />
      </MemoSection>

      <DataCaveats caveats={memo.dataCaveats} />

      <Sources sources={sources} />

      <p className="text-xs text-stone-400 text-center my-8">
        Generated by Claude (Anthropic). For research only, not investment advice.
      </p>
    </div>
  );
}
